FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install -y python3.6 \
    && apt-get install -y gcc \
    && apt-get install -y g++ \
    && apt-get install -y default-jre \
    && apt-get install -y nodejs